### ISSUE TITLE
no panning with min zoom

### ISSUE THREAD

**Issue by delstra** [jayrambhia/CropperNoCropper#10]
when i set min zoom to suppose 1.25 of the height, it works fine on supporting minimum zoom but after minimum zooming, I cannot pan the image within the square. The image snaps back to the minimum zoom set with center aligned.

**Comment by jayrambhia** [comment]
Fixed in 0.1.8.

**Comment by jayrambhia** [comment]
This issue is not yet fixed. #21

**Comment by jayrambhia** [comment]
Fixed in `0.1.9`.
