### ISSUE TITLE
Resizing final image

### ISSUE THREAD

**Issue by canberkcakmak** [jayrambhia/CropperNoCropper#11]
Hi, thanks for great library. How can i change the size final image px. For example when i use square final image gives 720x720 , or when i crop rectangle  height or width 720px. But i want to change this with 1280 or etc. How can i do? thank you.

**Comment by jayrambhia** [comment]
@canberkcakmak Since it's a cropper, it does not resize the bitmap at all. If you zoom in a lot, it would crop out that region without scaling it. So I think your input image width or height would be 720px. You can always resize the image manually once you have cropped it out.
