### ISSUE TITLE
how to get "bitmap" from our image-view(CropperView)?

### ISSUE THREAD

**Issue by shaileshmulange** [jayrambhia/CropperNoCropper#12]
I have tried to get "bitmap" from CropperView like our regular android image-view.
In android, we get "bitmap" using the following line
BitmapDrawable drawable = (BitmapDrawable) iv_image.getDrawable(); Bitmap image = drawable.getBitmap(); 
I have tried same thing with CropperView but getDrawable() method is not working.
I want bitmap for the change its brightness. I get the bitmap from CropperView using Bitmap bitmap = mImageView.getCroppedBitmap(); but unable to change brightness for image-view using this bitmap.

OR Simple, please tell me how to change brightness for image-view using CropperView.

**Comment by jayrambhia** [comment]
`CropperView.getCroppedBitmap()`
