### ISSUE TITLE
Resize Bitmap In replaceBitmap(bitmap) Method

### ISSUE THREAD

**Issue by hardz** [jayrambhia/CropperNoCropper#13]
Thanks for Awesome work on NoCropper.
Really Amazing Library to Achieve decent crop function.

In last update it's introduce replaceBitmap() method , this is the thing that i was looking for.
After block  "Bitmap is of different size. Not replacing" part in replaceBitmap method  it's resize bitmap for the first time, then it's work fine.

how to make it work fine ? for all the time including very first time.

**Comment by jayrambhia** [comment]
@hardz 
Are you using `0.1.6`?
If yes, can you elaborate? I am not able to follow the problem. An example code would be helpful. 

In 0.1.5, there was an issue with this method that even if you used replace, cropped out image would be based on the original bitmap. That was fixed 0.1.6.

**Comment by hardz** [comment]
@jayrambhia 
Thanks for Reply..!

Yes ! I'm using 0.1.6.

Let me Elaborate this issue perfectly.

Step 1 :
There in one bitmap(Original Bitmap) that i picked from gallery or camera, it will provided to CropperView using setImageBitmap(bitmap) method. Work fine !

Step 2 : 
After doing some process on Original Bitmap(Not resizing), it's remain same width and height, so i have to replace the bitmap as you provide in replaceBitmap(bitmap) method.

So,  here i am facing the strange behavior it won't work only very first time by using replaceBitmap(processed bitmap) Method, Very first time it resize original bitmap else where doing Great.

Hope you understand..!

**Comment by jayrambhia** [comment]
Let mw write a flow for this.
1. `cropper.setImageBitmap(mOrigBitmap);`
2. `Bitmap processedBitmap = process(mOrigBitmap);`
3. `cropper.replaceBitmap(processedBitmap);` -> Doesn't change anything?
4. `cropper.replaceBitmap(processedBitmap);` -> Works fine.

@hardz is this correct?

**Comment by jayrambhia** [comment]
Hey, @hardz can you confirm the issue? I'm unable to reproduce it. I may be missing something. It would be helpful if I could resolve this issue with your help.

**Comment by hardz** [comment]
Hey, @jayrambhia Yes i Confirm the issue ! It's work fine there is no problem in Cropper class.
it happened just because of loadNewImage(mOrigBitmap) that i use before passing the image to cropperview using setImageBitmap(loadNewImage(mOrigBitmap)), and i did't use that same way to 
replace processedBitmap using replaceBitmap(processedBitmap).

**changes in my worst flow is here**

cropper.setImageBitmap(loadNewImage(mOrigBitmap)); 
Bitmap processedBitmap = process(mOrigBitmap);
cropper.replaceBitmap(loadNewImage(processedBitmap)); -> Works fine for every time.

Thanks a Lot.
