### ISSUE TITLE
can project supports circle cropping  and other ratio  square  cropping

### ISSUE THREAD

**Issue by shuaimango** [jayrambhia/CropperNoCropper#17]
thank you very much

**Comment by jayrambhia** [comment]
This was made particularly for cropping images to square. There are some ways you can use this easily as circle cropper.

You can put a circular overlay over the cropper view and use crop to get a square image. Then write your own code to crop it in the shape of a circle. You can use canvas of bitmap and draw circular shape with clearing paint - http://stackoverflow.com/questions/11337679/porterduffxfermode-clear-a-section-of-a-bitmap and that would give you a circular looking image.

And, this project does not support other rectangle ratios, however, you may use `setMakeSquare(boolean status)` to not add padding to convert it to a square image.
