### ISSUE TITLE
CropperView class is becoming null if we use progaurd in my project

### ISSUE THREAD

**Issue by ReddiSekharNaidu** [jayrambhia/CropperNoCropper#18]
After enabling the progaurd in my project CropperNoCropper library is not working.
Its crashing and throwing the null pointer exception .

Can you please provide progaurd files which need to add in my project. 
Thanks in advance

**Comment by jayrambhia** [comment]
@ReddiSekharNaidu Can you post your proguard file as well as the crash logs?
