### ISSUE TITLE
min zoom is not working

### ISSUE THREAD

**Issue by HamidrezaAmz** [jayrambhia/CropperNoCropper#19]
I'm ok with setMaxZoom, but unfortunately setMinZoom is not working!
Here is my code

`// Set Bitmap
    cropperView.setImageBitmap(bitmap);
// Set Max and Min Cropping
    cropperView.setMaxZoom(1.5f);
    cropperView.setMinZoom(0.8f);`

**Comment by jayrambhia** [comment]
There was an issue with this as layout would override minzoom. It has been fixed in `0.1.9`.
