### ISSUE TITLE
Image initially zoomed

### ISSUE THREAD

**Issue by skined90** [jayrambhia/CropperNoCropper#22]
Is there any possibility to avoid image to be zoomed initially to 1:1 instead of its real size f.e. 16:9?

**Comment by jayrambhia** [comment]
Yes, I'll add that. Meanwhile, you can use `fitToCenter()` after setting the bitmap.

**Comment by jayrambhia** [comment]
Added in 0.2.0.

User `nocropper__fit_to_center=true` in xml or `CropperView#initWithFitToCenter(true)`
