### ISSUE TITLE
How to keep the Gridview always Visible

### ISSUE THREAD

**Issue by skhizerabass** [jayrambhia/CropperNoCropper#32]
I want to keep the grid lines always available, But i am not able to find any solution for that. Is there any solution to keep it visible all the time ?

**Comment by jayrambhia** [comment]
There's no way to do that right now. I'll add it to TO-DO.

**Comment by jayrambhia** [comment]
Fixed in 0.2.1

**Comment by skhizerabass** [comment]
Thanks man, It is working great now.

**Comment by skined90** [comment]
Is there any way to show the grid on start before any image manipulation?

**Comment by jayrambhia** [comment]
Hi @skined90 At the moment, there's no direct way to do that. I'll create a new issue and will work on it later.

Meanwhile, you could try this:

```
View gridView = cropperView.getChildAt(1);
if (gridView instanceof CropperGridView) {
  ((CropperGridView)gridView).setShowGrid(true);
}
```

**Comment by skined90** [comment]
@jayrambhia Thank you!
