### ISSUE TITLE
Is there anyway to find out the max zoom for my photos? e.g I want my higher dimension images that can only be zoomed till 1024px X 1024px dimensions

### ISSUE THREAD

**Issue by skhizerabass** [jayrambhia/CropperNoCropper#33]
Please let me know if there is any solution to calculate maxzoom for my desired dimensions ?

**Comment by jayrambhia** [comment]
I don't understand what you mean. Zoom is mainly in terms of scale. You can get zoom by

```
zoom = (max desired height or width) / (height or width of the bitmap)
```

I would advise you to load a scaled bitmap (lower res). Higher res image bitmaps may cause OOM issues.
