### ISSUE TITLE
CropperView on ViewPager Swipe problem

### ISSUE THREAD

**Issue by andrefpc** [jayrambhia/CropperNoCropper#36]
I have a problem in my CropperView, because the view Touch event don't prevent the ViewPager swipe, and this issue, makes it difficult to resize image.

**Comment by jayrambhia** [comment]
Hi @andrefpc, can you attach a screenshot or a gif/video about the behavior?

**Comment by stringybeans** [comment]
Hi @jayrambhia , I've had the same issue. When swiping to the left, the viewpager changes pages and the cropper doesn't move. When swiping to the right, there is stuttering since the cropper is on the last page.

https://giphy.com/gifs/lptwuCrr2oXHykRef3/html5

**Comment by jayrambhia** [comment]
Hi @andrefpc, @stringybeans I'm looking into this to see if I can provide some assistance and fix the issue. The cropper was not meant to be used with the ViewPager as both of them use scroll and drag. Meanwhile, can you implement something like this https://stackoverflow.com/questions/9650265/how-do-disable-paging-by-swiping-with-finger-in-viewpager-but-still-be-able-to-s to see if it works or not.

Thanks.
