### ISSUE TITLE
minimum zoom related to Image width and height.

### ISSUE THREAD

**Issue by iharshb** [jayrambhia/CropperNoCropper#37]
How can I set minimum zoom as per my Image width (For multiple Image selection)? Just like Instagram

Case 1: If I select a single image then Image should be zoom minimum as possible (Default).

Case 2: If I am selecting multiple Images then Images should be zoom minimum to image width (Just like `cropToCenter()`).

**Comment by jayrambhia** [comment]
You can calculate the minimum zoom that you want and use `cropper.setMinZoom(value)` method to set min zoom.
