### ISSUE TITLE
Not works when the image leaves the border of CropperView

### ISSUE THREAD

**Issue by tahirSmartboy** [jayrambhia/CropperNoCropper#4]
When we zoom the image in the CropperView and moves the image ...the image in the CropperView leaves the border and after this if we crop the image it gives this error....

java.lang.IllegalArgumentException: x + width must be <= bitmap.width()

**Comment by jayrambhia** [comment]
@tahirSmartboy Have you set any max zoom? Also, could you provide me the image dimensions? It would be very easy to reproduce and debug.

**Comment by tahirSmartboy** [comment]
No I haven’t set any max zoom ...

![screenshot_2015-11-30-20-53-54](https://cloud.githubusercontent.com/assets/10927636/11476481/f767e50c-97a8-11e5-8a36-a044d7294041.png)
![screenshot_2015-11-30-20-54-47](https://cloud.githubusercontent.com/assets/10927636/11476482/f7745fd0-97a8-11e5-948d-1727b4f105e8.png)

![Uploading Screenshot_2015-11-30-20-55-21.png…]()

these are the screenshots...

Dimes are : 960x1280

**Comment by jaumecolom** [comment]
It's happening the same to me, how can we solve it? Thanks

**Comment by jayrambhia** [comment]
yeah, I'm working on it.
