### ISSUE TITLE
Image Rotate issue on Some devices

### ISSUE THREAD

**Issue by ghost** [jayrambhia/CropperNoCropper#47]
we used  implementation 'com.fenchtose.nocropper:nocropper:0.3.1'  image rotate when we select image on samsung devices Samsung Galaxy A50 image rotate.

**Comment by jayrambhia** [comment]
Hi @Ashish19901, this is just an image cropper and does not provide functionalities to load the images. A lot of devices store the images with 90 degrees orientation and this data is available in the EXIF metadata of the image. You would have to write the image loading functionality by yourself. https://stackoverflow.com/questions/3647993/android-bitmaps-loaded-from-gallery-are-rotated-in-imageview
