### ISSUE TITLE
Can't pinch smoothly if image size is large. (Performance)

### ISSUE THREAD

**Issue by malikbilal1997** [jayrambhia/CropperNoCropper#49]

**Comment by jayrambhia** [comment]
A bitmap of size 1024*1024 will take 32 MB. So a bigger image will obviously cause a jank in the screen.

What you should do:

 1. Scale down the image before loading in the CropperView
  2. Use `CropInfo`and use it to crop the original Bitmap. https://github.com/jayrambhia/CropperNoCropper#cropinfo

You can also try `ScaledCropper` - https://github.com/jayrambhia/CropperNoCropper#how-to-use-it

**Comment by malikbilal1997** [comment]
Thanks for your reply. Is there any way to integrate Picasso or Glide with your library so that they can handle the scaling stuff?
