### ISSUE TITLE
Padding color doesn't get set from the setPaddingColor function

### ISSUE THREAD

**Issue by faizanabidnaqvi** [jayrambhia/CropperNoCropper#5]
I tried to use the setPaddingColor(color) function for the CropperView but it isn't saving it with the padding color. However, if I set the padding color from the layout file, then it works.

So I looked in your code and in your function (in CropperView), setPaddingColor doesn't set the padding color for the mImageView. 

On my side I just modified your code to fix it but just letting you know too. :)

**Comment by jayrambhia** [comment]
@faizanabidnaqvi Thanks for this. :) I'll update the code. You should send a pull request :)

**Comment by tahirSmartboy** [comment]
@jayrambhia can we remove the padding ?? i want just image .....of any aspect ratio...can i do this ..plz help .....?

**Comment by jayrambhia** [comment]
@tahirSmartboy The cropper gives the output as a square image. So minZoom or maxZoom won't help. If you want a quick fix, you should use the source code and remove padding commands. I'll try to add it by tonight.

**Comment by tahirSmartboy** [comment]
@jayrambhia thanks ...ill wait till tommorow .....because i also get some error on importing any package as an offline library :(

**Comment by jayrambhia** [comment]
Fixed it.
