### ISSUE TITLE
After crop some part of new image is coming with white space

### ISSUE THREAD

**Issue by anvesh523** [jayrambhia/CropperNoCropper#6]
http://imgur.com/a/j1Tew

I think some guy raised an issue about border,
![screenshot_2015-12-10-19-15-23](https://cloud.githubusercontent.com/assets/10726276/11717404/4f158be0-9f76-11e5-9490-a6f91c2640f0.png)

->
If imageview having free space it's creating white space along with image.
->

![crop_test](https://cloud.githubusercontent.com/assets/10726276/11717424/65d85858-9f76-11e5-8c2a-23143a382b67.jpg)

Please resolve this ASAP .....

Thank you.

**Comment by anvesh523** [comment]
I checked setMinZoom, it's not working !!!!!

**Comment by jayrambhia** [comment]
That's intentional. As mentioned in the description, the cropper gives a square image and if the image is not square, it adds padding to it and returns a square image. https://github.com/jayrambhia/CropperNoCropper/blob/master/nocropper/src/main/java/com/fenchtose/nocropper/CropperImageView.java#L606

You can set `paddingColor` in xml. Setting padding color is not currently supported in code.

**Comment by jayrambhia** [comment]
@anvesh523 Would you want an option where cropper doesn't add padding?

**Comment by anvesh523** [comment]
@jayrambhia  Yes, If either I am adding padding color or not my expected image is not coming (coming with some extra boarder), If you have any option please let me know without padding.

**Comment by anvesh523** [comment]
My suggestion if I can set setMinZoom is Math.min( width , height ) of image then It can't show the padding part. I tried in my code setMinZoom, But it's not working. I think It's taking max ( width, height ). Can you took it once please ....

**Comment by jayrambhia** [comment]
It will show the padding because the cropper gives out the square image and that was its primary function when I made it. I'll see if I can change it or not.

**Comment by anvesh523** [comment]
Thank you for that, If setMinZoom will works my problem is solved.

**Comment by jayrambhia** [comment]
Fixed this.
