### ISSUE TITLE
how to set max aspect ratio?

### ISSUE THREAD

**Issue by tahirSmartboy** [jayrambhia/CropperNoCropper#8]
thanks for the last update of removing the padding @jayrambhia, how can i set the max aspect ratio of the image while cropping?

**Comment by jayrambhia** [comment]
@tahirSmartboy Aspect ratio is 1:1 as this is a square cropper.

**Comment by tahirSmartboy** [comment]
but in the latest update you have given an option of setMakeSquare(boolean)

**Comment by tahirSmartboy** [comment]
how to set a minimum zoom out ratio for the image in the square window on make square as false

**Comment by jayrambhia** [comment]
You can use `setMinZoom()`
