### ISSUE TITLE
Custom crop frame

### ISSUE THREAD

**Issue by Vierco** [jayrambhia/CropperNoCropper#9]
Hi @jayrambhia 
Thanks for sharing this library.

It´s possible change the ratio of the crop frame?
Now its a square, but i need crop with a vertical rectangle form.
The output size now it´s 960x960, it´s possible change this too?¿

Thanks ind advanced :))

Sergio

**Comment by jayrambhia** [comment]
This cropper was specifically made to crop out square images so other ratios are not supported. There is an option `setMakeSquare(boolean makeSquare)` where if you pass `false`, it would not add padding to the final image to make it square. But I don't think that's what you want.

**Comment by Vierco** [comment]
Oks! Thanks for your quick answer!
